version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - POSTGRES_USER=utente
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=midb
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: utente
      POSTGRES_PASSWORD: password
      POSTGRES_DB: midb
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
